// Code generated by hertz generator.

package main

import (
	"context"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/obs-opentelemetry/provider"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/hertz-contrib/sessions"
	"github.com/hertz-contrib/sessions/cookie"
	"os"
	"personal-page-be/biz/container"
	"personal-page-be/biz/middlewire"
	"strings"
	"time"
)

var App *container.Container

func main() {
	App = container.GetContainer("conf/config.yaml")
	middlewire.InitAuth(App.Config.EffectiveJWTKey())

	var h *server.Hertz
	if endpoint := otelEndpoint(); endpoint != "" {
		p := provider.NewOpenTelemetryProvider(
			provider.WithServiceName(otelServiceName()),
			provider.WithExportEndpoint(endpoint),
			provider.WithInsecure(),
		)
		defer func() {
			_ = p.Shutdown(context.Background())
		}()

		tracer, cfg := hertztracing.NewServerTracer()
		h = server.Default(tracer, server.WithExitWaitTime(3*time.Second), server.WithHostPorts(App.Config.HttpConfig.Address), server.WithMaxRequestBodySize(100*1024*1024))
		h.Use(skipPingTrace(hertztracing.ServerMiddleware(cfg)))
	} else {
		h = server.Default(server.WithExitWaitTime(3*time.Second), server.WithHostPorts(App.Config.HttpConfig.Address), server.WithMaxRequestBodySize(100*1024*1024))
	}

	store := cookie.NewStore([]byte("secret"))
	h.Use(sessions.New("user", store))
	h.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"http://localhost:5173", "https://peacesheep.xyz", "https://www.peacesheep.xyz"},
		AllowCredentials: true,
		AllowWebSockets:  true,
	}))
	register(h)
	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		fmt.Println("hook 1")
		<-ctx.Done()
		fmt.Println("exit timeout!")
	})

	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		fmt.Println("hook 2")
	})
	h.Spin()
}

func otelEndpoint() string {
	endpoint := os.Getenv("OTEL_EXPORTER_OTLP_ENDPOINT")
	if endpoint == "" {
		endpoint = os.Getenv("OTEL_EXPORTER_OTLP_TRACES_ENDPOINT")
	}
	endpoint = strings.TrimSpace(endpoint)
	endpoint = strings.TrimPrefix(endpoint, "http://")
	endpoint = strings.TrimPrefix(endpoint, "https://")
	return strings.TrimRight(endpoint, "/")
}

func otelServiceName() string {
	if serviceName := strings.TrimSpace(os.Getenv("OTEL_SERVICE_NAME")); serviceName != "" {
		return serviceName
	}
	return "personal-page-be"
}

func skipPingTrace(next app.HandlerFunc) app.HandlerFunc {
	return func(ctx context.Context, c *app.RequestContext) {
		if string(c.Path()) == "/api/ping" {
			c.Next(ctx)
			return
		}
		next(ctx, c)
	}
}
