// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"personal-page-be/biz/middlewire"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	api := r.Group("/api")
	api.GET("/ping", App.GlobalService.HealthCheck)

	authApi := api.Group("/auth")
	authApi.POST("/login", App.UserService.Login)

	userApi := api.Group("/users")

	userApi.POST("/login", App.UserService.Login)
	userApi.GET("/logout", App.UserService.Logout)
	userApi.GET("/me", append(middlewire.UserMiddleware(), App.UserService.GetUserInfo)...)
	userApi.GET("/user-info", append(middlewire.UserMiddleware(), App.UserService.GetUserInfo)...)
	userApi.POST("/activate-code", append(middlewire.UserMiddleware(), App.UserService.GenerateActivateCode)...)
	userApi.POST("/register", App.UserService.Register)

	adminApi := api.Group("/admin")
	adminApi.GET("/users", append(middlewire.UserMiddleware(), App.UserService.ListUsers)...)
	adminApi.POST("/users/:id/role", append(middlewire.UserMiddleware(), App.UserService.UpdateUserRole)...)
	adminApi.POST("/users/:id/status", append(middlewire.UserMiddleware(), App.UserService.UpdateUserStatus)...)
	adminApi.POST("/users/:id/activation-code", append(middlewire.UserMiddleware(), App.UserService.RegenerateActivateCode)...)
	adminApi.POST("/users/:id/reset-test", append(middlewire.UserMiddleware(), App.UserService.ResetTestUser)...)
	adminApi.DELETE("/users/:id", append(middlewire.UserMiddleware(), App.UserService.DeleteTestUser)...)
	adminApi.GET("/files", append(middlewire.UserMiddleware(), App.FileService.ListAllFiles)...)
	adminApi.GET("/slides", append(middlewire.UserMiddleware(), App.SlideService.ListAdminSlides)...)
	adminApi.POST("/slides", append(middlewire.UserMiddleware(), App.SlideService.CreateSlide)...)
	adminApi.PUT("/slides/:id", append(middlewire.UserMiddleware(), App.SlideService.UpdateSlide)...)
	adminApi.DELETE("/slides/:id", append(middlewire.UserMiddleware(), App.SlideService.DeleteSlide)...)
	adminApi.POST("/slides/upload-deck", append(middlewire.UserMiddleware(), App.SlideService.UploadSlideDeck)...)
	adminApi.POST("/slides/upload-cover", append(middlewire.UserMiddleware(), App.SlideService.UploadSlideCover)...)
	adminApi.POST("/slides/sign-deck-upload", append(middlewire.UserMiddleware(), App.SlideService.SignSlideDeckUpload)...)
	adminApi.POST("/slides/sign-cover-upload", append(middlewire.UserMiddleware(), App.SlideService.SignSlideCoverUpload)...)
	adminApi.GET("/aichat/stats", append(middlewire.UserMiddleware(), App.AIChatService.GetAdminUsageStats)...)

	fileApi := api.Group("/files")

	fileApi.POST("", append(middlewire.UserMiddleware(), App.FileService.UploadFile)...)
	fileApi.GET("/mine", append(middlewire.UserMiddleware(), App.FileService.ListMyFiles)...)
	fileApi.GET("", App.FileService.FileInfo)
	fileApi.GET("/download", App.FileService.DownloadSignedFile)
	fileApi.GET("/direct-download", App.FileService.DownloadFile)
	fileApi.GET("/info", App.FileService.FileInfo)
	fileApi.DELETE("", append(middlewire.UserMiddleware(), App.FileService.DeleteFile)...)
	fileApi.DELETE("/:id", append(middlewire.UserMiddleware(), App.FileService.DeleteFile)...)

	messageApi := api.Group("/messages")
	messageApi.GET("/categories", App.MessageService.FindAllMessageCategories)
	messageApi.POST("", App.MessageService.SaveMessage)
	messageApi.GET("/reply", App.MessageService.GetReply)
	messageApi.POST("/reply", append(middlewire.UserMiddleware(), App.MessageService.AddReply)...)
	messageApi.GET("", App.MessageService.GetMessages)

	feedbackApi := api.Group("/feedback")
	feedbackApi.GET("/categories", App.MessageService.FindAllFeedbackCategories)
	feedbackApi.POST("", App.MessageService.SaveFeedback)
	feedbackApi.GET("/reply", App.MessageService.GetFeedbackReply)
	feedbackApi.POST("/reply", append(middlewire.UserMiddleware(), App.MessageService.AddFeedbackReply)...)
	feedbackApi.GET("/unread", append(middlewire.UserMiddleware(), App.MessageService.GetUnreadFeedback)...)
	feedbackApi.GET("", App.MessageService.GetFeedback)

	projectsApi := api.Group("/projects")
	projectsApi.GET("/num", App.ProjectService.GetNum)
	projectsApi.GET("", App.ProjectService.GetProjects)
	projectsApi.POST("", append(middlewire.UserMiddleware(), App.ProjectService.AddProject)...)
	projectsApi.DELETE("/:id", append(middlewire.UserMiddleware(), App.ProjectService.RemoveProject)...)

	slidesApi := api.Group("/slides")
	slidesApi.GET("", App.SlideService.ListPublicSlides)
	slidesApi.GET("/:slug/assets/*path", App.SlideService.ServeSlideAsset)
	slidesApi.GET("/:slug/cover", App.SlideService.ServeSlideCover)
	slidesApi.POST("/:slug/unlock", App.SlideService.UnlockSlide)

	api.POST("/aichat", App.AIChatService.SendMessage)
	api.GET("/aichat/stats", append(middlewire.UserMiddleware(), App.AIChatService.GetMyUsageStats)...)

	socket := r.Group("/socket")
	{
		socket.GET("/new-chat", App.ChatService.CreateChat)
		socket.GET("/join-chat", App.ChatService.JoinChat)
	}

}
