// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"personal-page-be/biz/infra/config"
	"personal-page-be/biz/infra/database"
	"personal-page-be/biz/infra/log"
	"personal-page-be/biz/internal/repo"
	"personal-page-be/biz/internal/service/aichat"
	"personal-page-be/biz/internal/service/blog"
	"personal-page-be/biz/internal/service/chat"
	"personal-page-be/biz/internal/service/file"
	"personal-page-be/biz/internal/service/global_service"
	"personal-page-be/biz/internal/service/message"
	"personal-page-be/biz/internal/service/project"
	"personal-page-be/biz/internal/service/slide"
	"personal-page-be/biz/internal/service/user"
)

// Injectors from wire.go:

func GetContainer(path string) *Container {
	configConfig := config.InitConfig(path)
	db := database.NewDatabase(configConfig)
	iRepository := repo.NewRepository(db)
	iUserService := user.NewUserService(iRepository, configConfig)
	logger := log.NewLogger()
	iFileService := file.NewFileService(iRepository, configConfig, logger)
	iGlobalService := global_service.NewGlobalService(iRepository, logger)
	iMessageService := message.NewMessageService(iRepository, configConfig, logger)
	iChatService := chat.NewChatService(iRepository, logger)
	iProjectService := project.NewProjectService(iRepository, iGlobalService, logger)
	iSlideService := slide.NewSlideService(iRepository, configConfig)
	iAIChatService := aichat.NewAIChatService(iRepository, configConfig, logger)
	iBlogService := blog.NewBlogService(iRepository, configConfig)
	container := NewContainer(configConfig, iUserService, iFileService, iGlobalService, iMessageService, iChatService, iProjectService, iSlideService, iAIChatService, iBlogService)
	return container
}
