// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"personal-page-be/biz/infra/cache"
	"personal-page-be/biz/infra/config"
	"personal-page-be/biz/infra/database"
	"personal-page-be/biz/infra/log"
	"personal-page-be/biz/internal/repo"
	"personal-page-be/biz/internal/service/chat"
	"personal-page-be/biz/internal/service/file"
	"personal-page-be/biz/internal/service/global_service"
	"personal-page-be/biz/internal/service/message"
	"personal-page-be/biz/internal/service/user"
)

// Injectors from wire.go:

func GetContainer(path string) *Container {
	configConfig := config.InitConfig(path)
	db := database.NewDatabase(configConfig)
	iRepository := repo.NewRepository(db)
	iUserService := user.NewUserService(iRepository)
	logger := log.NewLogger()
	iFileService := file.NewFileService(iRepository, logger)
	iGlobalService := global_service.NewGlobalService(iRepository, logger)
	iMessageService := message.NewMessageService(iRepository, configConfig)
	cacheCache := cache.NewCache()
	iChatService := chat.NewChatService(cacheCache, logger)
	container := NewContainer(configConfig, iUserService, iFileService, iGlobalService, iMessageService, iChatService)
	return container
}
