name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build project
        run: |
          chmod +x build.sh
          ./build.sh
        working-directory: . # 替换成你的仓库路径

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output