
name: build and push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: build
        run: |
          set CGO_ENABLED=0
          set GOOS=linux
          set GOARCH=amd64
          go build -o ./output/main
          cp ./run.sh ./output
      - name: push-main
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'git'
          server: '${{secrets.REMOTE_ADDRESS}}'
          ssh_private_key: ${{ secrets.GIT_SSH_KEY }}
          local_path: './output/*'
          remote_path: '/srv/personal-page-be'





